<?php

declare(strict_types=1);

namespace Choredon\Ui;

/**
 * Compiles a theme's tokens.json into:
 *  - a CSS file with custom properties
 *  - a Tailwind preset (as a JS file)
 *
 * Reference resolution: values like "{palette.triangle}" are replaced by
 * the concrete value found at that JSON path. Nested references are resolved
 * recursively.
 */
final class TokenCompiler
{
    /**
     * Flat map of token path => resolved value.
     * e.g. 'palette.triangle' => '#1E8FB8'
     */
    private array $resolved = [];

    public function __construct(private readonly array $tokens)
    {
        $this->resolve();
    }

    public static function fromFile(string $path): self
    {
        if (! is_readable($path)) {
            throw new \RuntimeException("Cannot read tokens file: {$path}");
        }

        $json = file_get_contents($path);
        $data = json_decode($json, true, 512, JSON_THROW_ON_ERROR);

        return new self($data);
    }

    /**
     * Flatten all token paths and resolve {...} references.
     */
    private function resolve(): void
    {
        $flat = $this->flatten($this->tokens);

        foreach ($flat as $path => $value) {
            $this->resolved[$path] = $this->resolveValue($value, $flat);
        }
    }

    private function flatten(array $data, string $prefix = ''): array
    {
        $flat = [];

        foreach ($data as $key => $value) {
            // Skip meta and comment keys.
            if (str_starts_with((string) $key, '$') || str_starts_with((string) $key, '_')) {
                continue;
            }

            $path = $prefix === '' ? (string) $key : "{$prefix}.{$key}";

            if (is_array($value) && ! $this->isLeafArray($value)) {
                $flat = array_merge($flat, $this->flatten($value, $path));
            } else {
                $flat[$path] = $value;
            }
        }

        return $flat;
    }

    /**
     * A leaf array is one where the token is a composite value
     * (e.g. type scale entries with size/line-height/weight).
     * We flatten these one level deeper so each property becomes a token.
     */
    private function isLeafArray(array $value): bool
    {
        // If every key is a scalar and the keys look like CSS property names,
        // treat as composite token that still needs flattening.
        // Simpler heuristic: always recurse into arrays. Composite handling
        // happens in the CSS emitter.
        return false;
    }

    private function resolveValue(mixed $value, array $flat): mixed
    {
        if (! is_string($value)) {
            return $value;
        }

        // Match {path.to.token} references.
        return preg_replace_callback(
            '/\{([a-z0-9._-]+)\}/i',
            function (array $match) use ($flat) {
                $path = $match[1];
                if (! array_key_exists($path, $flat)) {
                    throw new \RuntimeException("Unresolved token reference: {{$path}}");
                }
                return is_string($flat[$path])
                    ? $this->resolveValue($flat[$path], $flat)
                    : (string) $flat[$path];
            },
            $value
        );
    }

    /**
     * Emit CSS custom properties. Returns the CSS as a string.
     *
     * All tokens are emitted as `--{path-with-dashes}`.
     * The selector is configurable so themes can coexist via [data-theme="..."].
     */
    public function toCss(string $selector = ':root'): string
    {
        $lines = [];
        $lines[] = "/* Generated by Choredon TokenCompiler. Do not edit by hand. */";
        $lines[] = "/* Theme: " . ($this->tokens['$meta']['theme'] ?? 'unknown') . " */";
        $lines[] = "/* Version: " . ($this->tokens['$meta']['version'] ?? 'unknown') . " */";
        $lines[] = '';
        $lines[] = "{$selector} {";

        foreach ($this->cssProperties() as $name => $value) {
            $lines[] = "  {$name}: {$value};";
        }

        $lines[] = '}';

        return implode("\n", $lines) . "\n";
    }

    /**
     * Yield CSS custom property name => value pairs.
     * Nested paths are converted: 'semantic.color.surface.base' => '--color-surface-base'.
     * The 'semantic.' prefix is stripped because semantic tokens are the public API.
     * The 'palette.' prefix is kept as '--palette-*' because palette tokens are
     * theme-private and shouldn't be referenced by components.
     */
    private function cssProperties(): iterable
    {
        foreach ($this->resolved as $path => $value) {
            // Composite type-scale entries become multiple properties.
            if (is_array($value)) {
                foreach ($value as $subKey => $subValue) {
                    if (str_starts_with((string) $subKey, '_')) {
                        continue;
                    }
                    $name = $this->pathToCssVar("{$path}.{$subKey}");
                    yield $name => $subValue;
                }
                continue;
            }

            if (is_scalar($value)) {
                yield $this->pathToCssVar($path) => $value;
            }
        }
    }

    private function pathToCssVar(string $path): string
    {
        // Strip 'semantic.' prefix (public API).
        if (str_starts_with($path, 'semantic.')) {
            $path = substr($path, strlen('semantic.'));
        }
        // Keep 'palette.' and 'component.' prefixes.
        // Replace dots with dashes, dots in nested keys included.
        $name = str_replace('.', '-', $path);
        return "--{$name}";
    }

    /**
     * Emit a Tailwind preset file as JavaScript.
     * Returns the JS source as a string.
     *
     * Maps tokens to Tailwind theme keys using a convention:
     *  - semantic.color.*  -> theme.colors.{nested}
     *  - semantic.spacing  -> theme.spacing
     *  - semantic.radius   -> theme.borderRadius
     *  - semantic.font.*   -> theme.fontFamily.{name}
     *  - semantic.breakpoint -> theme.screens
     *
     * Tailwind classes reference the CSS variables, not the raw values.
     * This keeps the single source of truth in CSS and lets themes swap
     * at runtime without rebuilding Tailwind.
     */
    public function toTailwindPreset(): string
    {
        $colors     = $this->buildTailwindColors();
        $spacing    = $this->buildTailwindSpacing();
        $radius     = $this->buildTailwindRadius();
        $fontFamily = $this->buildTailwindFontFamily();
        $fontSize   = $this->buildTailwindFontSize();
        $screens    = $this->buildTailwindScreens();
        $boxShadow  = $this->buildTailwindShadow();

        $preset = [
            'colors'     => $colors,
            'spacing'    => $spacing,
            'borderRadius' => $radius,
            'fontFamily' => $fontFamily,
            'fontSize'   => $fontSize,
            'screens'    => $screens,
            'boxShadow'  => $boxShadow,
        ];

        $json = json_encode($preset, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

        return <<<JS
/* Generated by Choredon TokenCompiler. Do not edit by hand. */
/* Classes reference CSS variables, not raw values, so themes swap at runtime. */

module.exports = {
  theme: {
    extend: {$json}
  }
};
JS;
    }

    private function buildTailwindColors(): array
    {
        $colors = [];
        foreach ($this->resolved as $path => $value) {
            if (! str_starts_with($path, 'semantic.color.')) continue;
            if (! is_scalar($value)) continue;

            $relative = substr($path, strlen('semantic.color.'));
            $parts = explode('.', $relative);
            $cssVar = "var(--" . str_replace('.', '-', $relative) . ")";

            $this->setNested($colors, $parts, $cssVar);
        }
        return $colors;
    }

    private function buildTailwindSpacing(): array
    {
        $spacing = [];
        foreach ($this->resolved as $path => $value) {
            if (! str_starts_with($path, 'semantic.spacing.')) continue;
            if (! is_scalar($value)) continue;

            $key = substr($path, strlen('semantic.spacing.'));
            $spacing[$key] = "var(--spacing-{$key})";
        }
        return $spacing;
    }

    private function buildTailwindRadius(): array
    {
        $radius = [];
        foreach ($this->resolved as $path => $value) {
            if (! str_starts_with($path, 'semantic.radius.')) continue;
            if (! is_scalar($value)) continue;

            $key = substr($path, strlen('semantic.radius.'));
            $radius[$key] = "var(--radius-{$key})";
        }
        return $radius;
    }

    private function buildTailwindFontFamily(): array
    {
        $fonts = [];
        foreach ($this->resolved as $path => $value) {
            if (! str_starts_with($path, 'semantic.font.')) continue;
            if (! is_scalar($value)) continue;
            if (str_contains($path, 'font-weight')) continue;

            $key = substr($path, strlen('semantic.font.'));
            // Tailwind fontFamily expects array of font names, but
            // CSS-var-backed is: [`var(--font-...)`, ...system fallbacks].
            $fonts[$key] = ["var(--font-{$key})"];
        }
        return $fonts;
    }

    private function buildTailwindFontSize(): array
    {
        $sizes = [];
        $scale = $this->tokens['semantic']['type-scale'] ?? [];
        foreach ($scale as $name => $def) {
            if (str_starts_with((string) $name, '_')) continue;
            if (! is_array($def)) continue;

            // Tailwind fontSize can be [size, {lineHeight, letterSpacing, fontWeight}].
            $size = "var(--type-scale-{$name}-size)";
            $extras = [];
            if (isset($def['line-height'])) {
                $extras['lineHeight'] = "var(--type-scale-{$name}-line-height)";
            }
            if (isset($def['letter-spacing'])) {
                $extras['letterSpacing'] = "var(--type-scale-{$name}-letter-spacing)";
            }
            if (isset($def['weight'])) {
                $extras['fontWeight'] = "var(--type-scale-{$name}-weight)";
            }

            $sizes[$name] = $extras === [] ? $size : [$size, $extras];
        }
        return $sizes;
    }

    private function buildTailwindScreens(): array
    {
        $screens = [];
        $breakpoints = $this->tokens['semantic']['breakpoint'] ?? [];
        foreach ($breakpoints as $name => $value) {
            if (str_starts_with((string) $name, '_')) continue;
            if (! is_scalar($value)) continue;
            $screens[$name] = $value;
        }
        return $screens;
    }

    private function buildTailwindShadow(): array
    {
        $shadows = [];
        foreach ($this->resolved as $path => $value) {
            if (! str_starts_with($path, 'semantic.shadow.')) continue;
            if (! is_scalar($value)) continue;

            $key = substr($path, strlen('semantic.shadow.'));
            $shadows[$key] = "var(--shadow-{$key})";
        }
        return $shadows;
    }

    private function setNested(array &$target, array $path, mixed $value): void
    {
        $current = &$target;
        foreach ($path as $i => $segment) {
            if ($i === count($path) - 1) {
                // If the segment is 'DEFAULT' Tailwind convention, set at current level.
                // We handle the common case: first segment is the color name,
                // subsequent segments are variants. If there's only one segment,
                // set directly.
                if (count($path) === 1) {
                    $current[$segment] = $value;
                } else {
                    $current[$segment] = $value;
                }
                return;
            }
            if (! isset($current[$segment]) || ! is_array($current[$segment])) {
                $current[$segment] = [];
            }
            $current = &$current[$segment];
        }
    }

    public function resolvedTokens(): array
    {
        return $this->resolved;
    }
}
